// GENERATED by design/icon-set/gen-hero.mjs from design/icon-set/icons.mjs.
// Do not hand-edit: change the icon there and re-run the generator.
//
// "Offset ink" style: a clean forest line over a flat colour that sits a
// couple of units down-left, like a misregistered print. 64x64 viewBox.

export const HERO_ART = {
  apple: (
    <><g><g transform="translate(-2.4 2.2)"><path d="M32 21c4-6 14-6 18 2s0 22-8 30c-4 4-8 2-10 2s-6 2-10-2c-8-8-12-22-8-30s14-8 18-2z" fill="#e8695a" /><path d="M34 15c4-6 12-6 14-2-4 6-10 6-14 2z" fill="#8cc472" /></g><path d="M32 21c4-6 14-6 18 2s0 22-8 30c-4 4-8 2-10 2s-6 2-10-2c-8-8-12-22-8-30s14-8 18-2z" fill="none" stroke="#14382a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /><path d="M32 21c-1-4 0-8 3-11" fill="none" stroke="#14382a" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /><path d="M34 15c4-6 12-6 14-2-4 6-10 6-14 2z" fill="none" stroke="#14382a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /></g></>
  ),
  milk: (
    <><g><g transform="translate(-2.4 2.2)"><path d="M25 17h14v4c0 3 6 6 6 12v20a4 4 0 0 1-4 4H23a4 4 0 0 1-4-4V33c0-6 6-9 6-12z" fill="#bfe0f2" /><path d="M19 34h26v9H19z" fill="#a6d3ee" /></g><path d="M25 17h14v4c0 3 6 6 6 12v20a4 4 0 0 1-4 4H23a4 4 0 0 1-4-4V33c0-6 6-9 6-12z" fill="none" stroke="#14382a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /><path d="M19 34h26v9H19z" fill="none" stroke="#14382a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /><path d="M24 11h16a1.5 1.5 0 0 1 1.5 1.5V17H22.5v-4.5A1.5 1.5 0 0 1 24 11z" fill="#fff" stroke="#14382a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /></g></>
  ),
  egg: (
    <><g><g transform="translate(-2.4 2.2)"><path d="M24 17c7 0 11 9 11 17 0 7-5 12-11 12S13 41 13 34c0-8 4-17 11-17z" fill="#f6e9c9" /><path d="M38 23c7 0 12 9 12 18 0 7-5 12-12 12s-12-5-12-12c0-9 5-18 12-18z" fill="#f3d98c" /></g><path d="M24 17c7 0 11 9 11 17 0 7-5 12-11 12S13 41 13 34c0-8 4-17 11-17z" fill="none" stroke="#14382a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /><path d="M38 23c7 0 12 9 12 18 0 7-5 12-12 12s-12-5-12-12c0-9 5-18 12-18z" fill="none" stroke="#14382a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /></g></>
  ),
  fish: (
    <><g><g transform="translate(-2.4 2.2)"><path d="M14 32c6-10 14-14 24-14 6 0 11 5 16 14-5 9-10 14-16 14-10 0-18-4-24-14z" fill="#a6d3ee" /><path d="M14 32l-8-9v18z" fill="#bfe0f2" /></g><path d="M14 32c6-10 14-14 24-14 6 0 11 5 16 14-5 9-10 14-16 14-10 0-18-4-24-14z" fill="none" stroke="#14382a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /><path d="M14 32l-8-9v18z" fill="none" stroke="#14382a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /><path d="M40 27a2 2 0 1 0 4 0 2 2 0 1 0-4 0" fill="none" stroke="#14382a" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" /><path d="M30 22c-2 6-2 14 0 20" fill="none" stroke="#14382a" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" opacity="0.6" /></g></>
  ),
  greens: (
    <><g><g transform="translate(-2.4 2.2)"><path d="M32 11c12 6 18 18 14 30-3 8-9 13-14 14-5-1-11-6-14-14C14 29 20 17 32 11z" fill="#8cc472" /></g><path d="M32 11c12 6 18 18 14 30-3 8-9 13-14 14-5-1-11-6-14-14C14 29 20 17 32 11z" fill="none" stroke="#14382a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /><path d="M32 60V20" fill="none" stroke="#14382a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /><path d="M32 30c-4-1-7-4-9-8M32 40c4-1 7-4 9-8M32 47c-4-1-7-4-9-8M32 33c4-1 7-4 9-8" fill="none" stroke="#14382a" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" opacity="0.7" /></g></>
  ),
  carrot: (
    <><g transform="rotate(-24 32 38)"><g transform="translate(-2.4 2.2)"><path d="M32 60c-4-6-12-18-11-30 1-8 5-12 11-12s10 4 11 12c1 12-7 24-11 30z" fill="#f0913e" /><path d="M32 18c-4-6-10-8-14-6 3 4 8 7 14 6z" fill="#8cc472" /><path d="M32 18c4-6 10-8 14-6-3 4-8 7-14 6z" fill="#8cc472" /><path d="M32 18c-1-6 0-11 3-14 2 5 1 10-3 14z" fill="#8cc472" /></g><path d="M32 60c-4-6-12-18-11-30 1-8 5-12 11-12s10 4 11 12c1 12-7 24-11 30z" fill="none" stroke="#14382a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /><path d="M26 31h7M27 41h6" fill="none" stroke="#14382a" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" /><path d="M32 18c-4-6-10-8-14-6 3 4 8 7 14 6z" fill="none" stroke="#14382a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /><path d="M32 18c4-6 10-8 14-6-3 4-8 7-14 6z" fill="none" stroke="#14382a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /><path d="M32 18c-1-6 0-11 3-14 2 5 1 10-3 14z" fill="none" stroke="#14382a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /></g></>
  ),
}
