#!/usr/bin/env node
// Runs before `vite build` (and can be run standalone in dev). Parses every
// content/posts/*.md and writes ONE generated file: the post index, already
// filtered to published posts, with NO article HTML in it. Article bodies
// are reached separately via the markdown Vite plugin (vite.config.js) so
// the /resources listing page never has to load 80 posts' worth of HTML just
// to render a grid of cards.
//
// Set PANTRY_DRAFTS=1 to include future-dated posts locally, so a post can be
// proofed before its publishDate arrives.
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { getPublishedPosts, loadAllPosts, sydneyToday } from './lib/posts.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outFile = resolve(root, 'src/site/content/posts.index.generated.js')

const all = loadAllPosts()
const actuallyPublished = getPublishedPosts(all, sydneyToday())
const includeDrafts = process.env.PANTRY_DRAFTS === '1'
const published = includeDrafts ? all : actuallyPublished

if (includeDrafts && all.length !== actuallyPublished.length) {
	console.log(`[build-content] PANTRY_DRAFTS=1 — including ${all.length - actuallyPublished.length} unpublished post(s)`)
}

const index = published.map(({ html, ...meta }) => meta)

const banner = `// GENERATED by scripts/build-content.mjs from content/posts/*.md — do not edit.
// Already filtered to publishDate <= today (Australia/Sydney): an unpublished
// post's title, slug, excerpt and reading time never reach this file, let
// alone the client bundle.
`

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, `${banner}\nexport const posts = ${JSON.stringify(index, null, 2)}\n`)

console.log(`[build-content] wrote ${index.length}/${all.length} published post(s) to ${outFile.replace(root + '/', '')}`)
