// Emits ../pantry/src/components/icons/foodArt.generated.ts from the icon set.
// Re-run after editing icons.mjs: npm run icons:app
//
// The app draws these with react-native-svg, so this emits path DATA (fills
// resolved to hex, split into the offset colour layer and the ink layer) rather
// than JSX — same split renderSvg does in icons.mjs.
import { ICONS, INK, OFFSET } from './icons.mjs';
import { writeFileSync } from 'node:fs';

const OUT = new URL('../../../pantry/src/components/icons/foodArt.generated.ts', import.meta.url);

function q(s) { return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`; }

function part(icon, p) {
  const fillHex = p.fill ? icon.pal[p.fill] || icon.pal.main : null;
  const lineFace = p.face ? icon.pal[p.face] : p.fill === null ? '#fff' : null;
  return { fillHex, lineFace };
}

const names = Object.keys(ICONS);
const entries = names.map((k) => {
  const icon = ICONS[k];
  const fills = [], lines = [];
  for (const p of icon.parts) {
    const { fillHex, lineFace } = part(icon, p);
    const tf = p.tf ? `, tf: ${q(p.tf)}` : '';
    if (fillHex) fills.push(`{ d: ${q(p.d)}, fill: ${q(fillHex)}${tf} }`);
    if (p.line) {
      const o = p.o ? `, o: ${p.o}` : '';
      const face = lineFace ? `, fill: ${q(lineFace)}` : '';
      lines.push(`{ d: ${q(p.d)}, w: ${p.w ?? 2.4}${o}${face}${tf} }`);
    }
  }
  const tf = icon.tf ? `\n\t\ttf: ${q(icon.tf)},` : '';
  return `\t${k}: {${tf}\n\t\tfills: [\n${fills.map((f) => `\t\t\t${f},`).join('\n')}\n\t\t],\n\t\tlines: [\n${lines.map((l) => `\t\t\t${l},`).join('\n')}\n\t\t],\n\t},`;
});

writeFileSync(OUT, `// GENERATED by pantry-website/design/icon-set/gen-app.mjs from icons.mjs.
// Do not hand-edit: change the icon there and run \`npm run icons:app\` in the
// website repo.
//
// "Offset ink" style: a clean forest line over flat colour that sits a couple
// of units down-left, like a misregistered print. 64x64 viewBox.

export const FOOD_ART_INK = ${q(INK)};
export const FOOD_ART_OFFSET = { dx: ${OFFSET.dx}, dy: ${OFFSET.dy} };

export type FoodArtFill = { d: string; fill: string; tf?: string };
export type FoodArtLine = { d: string; w: number; o?: number; fill?: string; tf?: string };
export type FoodArt = { tf?: string; fills: FoodArtFill[]; lines: FoodArtLine[] };

export type FoodIconName =
${names.map((n) => `\t| '${n}'`).join('\n')};

export const FOOD_ART: Record<FoodIconName, FoodArt> = {
${entries.join('\n')}
};
`);
console.log('wrote foodArt.generated.ts', names.length, 'icons');
