// Emits src/site/components/heroFoodArt.jsx from the icon set. Re-run after
// editing icons.mjs: node design/icon-set/gen-hero.mjs
import { ICONS, renderJsx } from './icons.mjs';
import { writeFileSync } from 'node:fs';
const HERO = ['apple', 'milk', 'egg', 'fish', 'greens', 'carrot'];
const body = HERO.map((k) => `  ${k}: (\n    <>${renderJsx(ICONS[k])}</>\n  ),`).join('\n');
writeFileSync(new URL('../../src/site/components/heroFoodArt.jsx', import.meta.url),
`// GENERATED by design/icon-set/gen-hero.mjs from design/icon-set/icons.mjs.
// Do not hand-edit: change the icon there and re-run the generator.
//
// "Offset ink" style: a clean forest line over a flat colour that sits a
// couple of units down-left, like a misregistered print. 64x64 viewBox.

export const HERO_ART = {
${body}
}
`);
console.log('wrote heroFoodArt.jsx', HERO.join(', '));
